# The URL the site will be built for
base_url = "https://boxxy.dev"
title = "Boxxy Terminal"
description = "A powerful CLI tool to simplify your development workflow"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
insert_anchor_links = "left"

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
